name: artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    # - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
    #   run: go build ${{ env.FILE_NAME }}.go

    # - name: Build ${{ env.FILE_NAME }} for windows-latest
    #   run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .



  
